# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddbdb5093cd198cb90ac05b955e1dba4aaceb6a8a5f91eaea18cb006c626a56a07e36cbf48970b740ab9f517dc737568491589ca2ec997a5033455648a84291a

test:
  secret_key_base: 2a5c8b241eee20b9d6d1c1e1c739891433ff8bfbe2dc57ad8373c27123f9aff4723365e591a23fe1b39ba2c359dee4783b8f23047ce3d458b0e001bf90cd1873

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
